deb2xbps june 2023 build 0.4.1

diff --git a/deb2xbps b/deb2xbps
--- a/deb2xbps
+++ b/deb2xbps
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [[ $(arch) != "x86_64" ]]; then
+echo "The deb2xbps tool cannot be executed on a 32-bit system. Support for 32-bit systems has been discontinued."
+exit 1
+fi
+
 clear
 echo "#################################################################"
 echo "Checking for updates in Void Linux..." 
@@ -30,7 +35,7 @@ echo " ██   ██ █████   ██████   █████   
 echo " ██   ██ ██      ██   ██ ██       ██ ██  ██   ██ ██           ██ "
 echo " ██████  ███████ ██████  ███████ ██   ██ ██████  ██      ███████ "
 echo "#################################################################"
-echo "build-latest: 0.4.0"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
+echo "build-latest: 0.4.1"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
 echo "deb2xbps-github: https://github.com/manoel-linux/deb2xbps-shlibs-voidpackages"
 echo "xdeb-github: https://github.com/toluschr/xdeb"
 echo "The support for 32-bit .deb packages has been discontinued."
